# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Install the codecov pip dependency
install:
  - pip install coveralls

# Run the unit test
script:
  - pytest

# Push the results back to codecov
after_success:
  - coveralls
