# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Install the tools for pytest and coveralls
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install jinja2
  - pip install coveralls
  - pip install Flask

# Run the unit test
script:
  - pytest --cov=src/ 

# Push the results back to coveralls
after_success:
  - coveralls
