# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Install the tools for pytest and coveralls
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls

# Run the unit test
script:
  - pytest --cov=test/ --repeat 10 

# Push the results back to coveralls
after_success:
  - coveralls


